{
    "name": "PMS",
    "version": "1.0",
    "category": "Services",
    "depends": [
        "base",
        "contacts",
        "account",
        "documents",
        "helpdesk",
        "website",
        "website_blog",
        "web",
        "sign",
        "portal",
        "event",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/announcements/sample_posts.xml",
        "data/announcements/amenities.xml",
        "data/announcements/policies.xml",
        "data/work_permits_seeder.xml",
        "data/teams.xml",
        "data/documents.xml",
        "views/homepage.xml",
        # 'views/sample.xml',
        # 'views/sample2.xml',
        # 'views/form.xml',
        # 'views/thank_you.xml',
        # 'views/sample4.xml',
        "views/pdf/amenities_sign.xml",
        "views/pdf/amenities_template.xml",
        "views/pdf/pet_registration_template.xml",
        "views/pdf/unit_owner_info_template.xml",
        "views/pdf/tenant_info_template.xml",
        "views/forms/helpdesk.xml",
        "views/forms/form_wizard.xml",
        "views/forms/form_reviewer.xml",
        "views/forms/concern_slip_form.xml",
        "views/forms/amenities_form.xml",
        "views/forms/pet_registration_form.xml",
        "views/forms/unit_owner_info_form.xml",
        "views/forms/tenant_info_form.xml",
        "views/forms/cctv_request_form.xml",
        "views/forms/gate_pass_form.xml",
        "views/forms/vehicle_pass_form.xml",
        "views/forms/user_info_form.xml",
        "views/properties/property_unit.xml",
        "views/properties/property_ownership.xml",
        "views/properties/property_tenancy.xml",
        "views/properties/property_building.xml",
        "views/properties/property_contacts.xml",
        # "views/properties/contacts_form_modifications.xml",
        "views/website/website_modifications.xml",
        "views/website/portal_modifications.xml",
        "views/website/homepage.xml",
        "views/website/forms_homepage.xml",
        "views/website/gate_pass_form_web.xml",
        "views/website/cctv_request_form_web.xml",
        "views/website/amenities_form_web.xml",
        "views/website/pet_registration_web.xml",
        "views/website/base/person_base_form_web.xml",
        "views/website/base/spouse_person_base_form_web.xml",
        "views/website/base/vehicle_base_form_web.xml",
        "views/website/base/multiple_person_base_form_web.xml",
        "views/website/unit_owner_info_form_web.xml",
        "views/website/tenant_info_form_web.xml",
        "views/website/vehicle_pass_form_web.xml",
        "views/website/work_permit_form_web.xml",
        "views/website/ticket_submission_web.xml",
        "views/website/user_info_form_web.xml",
        "views/website/concern_slip_form_web.xml",
        "views/website/res_partner_details.xml",
        "views/website/res_partner_update.xml",
        # "views/website/thank_you.xml",
        "views/menu.xml",
    ],
    "license": "LGPL-3",
    "author": "Jerick Cumayas",
}
